### ISSUE TITLE
Missing handler registration for GetByIdQuery : IQuery<Option<object>> standard query

### ISSUE THREAD

**Issue by mroncev** [ironcev/Pragmatic#19]
Can you please add handler for GetByIdQuery (the option object version) to the list of standard definitions. Currently, if you try something like this:

<code>QueryExecutor.GetById(entityType, id)</code>

the following error is thrown:

![error](https://cloud.githubusercontent.com/assets/6671657/8980056/503639ba-36ae-11e5-8576-ebc3b59284a8.png)

Thank you!

**Comment by ironcev** [comment]
Marin, thanks for pointing out the bug!

The problem was in the registration of the standard handler which was missing. There is a new method added to the `StandardInteractionHandlerRegistration` class called `RegisterStandardNonGenericGetByIdQueryHandler`. Just add a call to it below the call for the `RegisterStandardInteractionHandlersForEntities` method and provide the `typeof(GetByIdQueryHandler)` as the argument.

A new NuGet package is published for the *Pragmatic.StructureMap*. Just download it and the method will be available.

Unfortunately, there are not real automated tests in Pragmatic right now so I cannot guarantee that this actually works :-( but I assume it should. Please let me know if you face any additional issues.

**Comment by mroncev** [comment]
It is working fine.

Thank you for the quick fix!
